config/routes.rb
Rails.application.routes.draw do
  resources :users

  root 'conversations#index'
  resources :agents
  resources :conversations do
    member do
      post 'increment'
      get 'reset'
      post 'start_simulation'
    end
  end
  resources :messages
  resources :user
  resource :session, only: [:new, :create, :destroy]
  get "signup" => "users#new"
  get "signin" => "sessions#new"

end

app/models/conversation.rb
class Conversation < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :conversation_agents, dependent: :destroy
  has_many :agents, through: :conversation_agents

  belongs_to :user

  accepts_nested_attributes_for :agents, allow_destroy: true

  validate :validate_agents_count


  def new_message
    ActiveRecord::Base.transaction do
      agent = agents.select{ |agent| agent != last_message_agent }.sample
      message_text = generate_message_text(agent)
      messages.create(agent: agent, message_text: message_text)
    end
  end

  def last_message
    messages.last
  end

  def last_message_agent
    last_message&.agent
  end

  def generate_message_text(agent)
    system_prompt = agent.system_prompt

    context_prompt = prompt(agent)

    message = PromptService.new(content: context_prompt, system: system_prompt, model: agent.model, temperature: agent.temperature).prompt

    if Agent::OPENAI_MODELS.include?(agent.model)
      message["choices"][0]["message"]["content"]
    elsif Agent::COHERE_MODELS.include?(agent.model)
      message["text"]
    elsif Agent::CLAUDE_MODELS.include?(agent.model)
      message["content"].first["text"]
    end
  end

  def prompt(agent)
    """
    Continue.

    Here's the history of the conversation so far:
    #{messages.map { |message| "#{message.agent.name} said: #{message.message_text}" }.join("\n")}
    """
  end

  def reset
    messages.destroy_all
  end

  def simulate_conversation(steps)
    steps.times do
      new_message
      sleep(5)
    end
  end



  private

  def validate_agents_count
    errors.add(:agents, "must be between 1 and 4") unless agents.size.between?(1, 4)
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

  before_action :require_user_signin

  def index
    @conversations = current_user.conversations
  end

  def show
    @conversation = Conversation.find(params[:id])
    @agents = @conversation.agents

  end

  def edit
    @conversation = Conversation.find(params[:id])
    @agents = Agent.all
  end

  def update
    @conversation = Conversation.find(params[:id])
    @agents = Agent.all

    agent_ids = params[:conversation][:agent_ids]
    if agent_ids.present?
      selected_agents = Agent.find(agent_ids)
      @conversation.agents = selected_agents
    end

    if @conversation.update(conversation_params)
      redirect_to @conversation
    else
      render 'edit'
    end
  end

  def destroy
    @conversation = Conversation.find(params[:id])
    @conversation.destroy

    redirect_to conversations_path
  end

  def reset
    @conversation = Conversation.find(params[:id])
    @conversation.reset
    redirect_to @conversation
  end

  def new
    @conversation = Conversation.new
    @agents = current_user.agents
  end

  def create
    @conversation = Conversation.new(conversation_params)
    @conversation.user_id = current_user.id
    @agents = current_user.agents

    agent_ids = params[:conversation][:agent_ids]
    if agent_ids.present?
      selected_agents = Agent.find(agent_ids)
      @conversation.agents = selected_agents
    end

    if @conversation.save
      redirect_to @conversation
    else
      render 'new'
    end
  end


  def increment
    @conversation = Conversation.find(params[:id])
    @message = @conversation.new_message

    respond_to do |format|
      format.html { redirect_to @conversation }
      format.turbo_stream
    end
  end

  def start_simulation
    steps = params[:steps].to_i
    @conversation = Conversation.find(params[:id])
    ConversationSimulationJob.perform_later(@conversation.id, steps, current_user.email)
    redirect_to @conversation, notice: 'Simulation started'
  end

  private

  def conversation_params
    params.require(:conversation).permit(:title, :topic, agent_ids: [])
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_form.html.erb
<div class="card-body">
    <%= form_for @conversation, html: { class: 'form-horizontal' } do |f| %>
      <div class="form-group row">
        <%= f.label :title, class: 'col-md-3 col-form-label' %>
        <div class="col-md-9">
          <%= f.text_field :title, class: 'form-control' %>
        </div>
      </div>

        <div class="form-group row my-3">
            <%= f.label "Conversation topic", class: 'col-md-3 col-form-label' %>
            <div class="col-md-9">
            <%= f.text_area :topic, class: 'form-control' %>
        </div>

      <div class="form-group row my-3">
        <%= f.label :agents, "Select Agents (1-4)", class: 'col-md-3 col-form-label' %>
        <div class="col-md-9">
          <% @agents.each do |agent| %>
            <div class="form-check">
              <%= check_box_tag 'conversation[agent_ids][]', agent.id, @conversation.agents.include?(agent), id: "agent_#{agent.id}", class: 'form-check-input' %>
              <%= label_tag "agent_#{agent.id}", agent.name, class: 'form-check-label' %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-md-9 offset-md-3">
          <%= f.submit "Create Conversation", class: 'btn btn-success' %>
        </div>
      </div>
    <% end %>
  </div>

app/views/conversations/_message.html.erb
<% @message = message %>
<div data-controller="message-animation" data-animate="<%= animate ? 'true' : 'false' %>" class="my-3">
    <div class="card-header fw-bold">
        <%= @message.agent.name %>
    </div>
    <div class="card-body">
        <p class="card-text" data-message-animation-target="text"><%= @message.message_text %></p>
    </div>
</div>

app/views/conversations/edit.html.erb
<div class="container mt-5">
    <div class="row">
      <div class="col-md-8 offset-md-2">
        <div class="card">
          <div class="card-header">
            <h2>Edit Conversation</h2>
          </div>
          <%= render 'form', conversation: @conversation, agents: @agents %>
        </div>
      </div>
    </div>
  </div>

app/views/conversations/increment.turbo_stream.erb
<%= turbo_stream.append "messages", partial: "message", locals: { message: @message, animate: true } %>

app/views/conversations/index.html.erb
<div class="container mt-5">
    <h1 class="mb-4">Conversations</h1>
    <%= link_to 'Create Conversation', new_conversation_path, class: 'btn btn-primary mb-3' %>
  
    <div class="row">
      <% @conversations.each do |conversation| %>
        <div class="col-md-4 mb-4">
          <div class="card">
            <div class="card-body">
              <h4 class="card-title"><%= conversation.title %></h4>
              <p class="card-text">Agents: <%= conversation.agents.count %></p>
              <%= link_to 'View', conversation_path(conversation), class: 'btn btn-primary' %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  

app/views/conversations/new.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <div class="card">
        <div class="card-header">
          <h2>Create New Conversation</h2>
        </div>
        <%= render 'form', conversation: @conversation, agents: @agents %>
      </div>
    </div>
  </div>
</div>

app/views/conversations/show.html.erb
<div class="container mt-4">
    <h1 class="display-4"><%= @conversation.title %></h1>
    <p class="lead">A conversation between <%= @agents.count %> agents.</p>
    
    <div class="card my-4">
      <div class="card-header">
        Agents Involved
      </div>
      <ul class="list-group list-group-flush">
        <% @agents.each do |agent| %>
          <li class="list-group-item"><%= agent.name %></li>
        <% end %>
      </ul>
    </div>

    <div class="card my-4">
      <div class="card-header">
        Conversation Topic
      </div>
      <div class="card-body">
        <p class="card-text"><%= @conversation.topic %></p>
      </div>
    </div>
  
    <div class="card my-4">
      <div class="card-header">
        Conversation Controls
      </div>
      <div class="card-body">
        <div class="row">
          <div class="col-3">
          <%= turbo_frame_tag "increment_button" do %>
            <%= link_to 'Increment Conversation', increment_conversation_path(@conversation), class: 'btn btn-primary', data: { turbo_method: :post, turbo_frame: "increment_button" } %>
          <% end %>
          <%= turbo_frame_tag "simulation_button" do %>
            <%= form_with(url: start_simulation_conversation_path(@conversation), local: true) do |form| %>
              <%= form.number_field :steps, placeholder: "Number of increments" %>
              <%= form.submit "Start Simulation" %>
            <% end %>
          <% end %>
          </div>
          <div class="col-3">
            <div class="btn-group" role="group">
              <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                Settings
              </button>
              <ul class="dropdown-menu">
                <li><%= link_to 'Edit Conversation', edit_conversation_path(@conversation), class: 'dropdown-item' %></li>
                <li><%= link_to 'Reset Conversation', reset_conversation_path(@conversation), class: 'dropdown-item' %></li>
                <li><%= button_to 'Delete Conversation', conversation_path(@conversation), method: :delete, class: 'dropdown-item' %></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div id="messages">
      <% if @conversation.messages.any? %>
        <% @conversation.messages.each do |message| %>
              <%= render 'message', message: message, animate: false %>
        <% end %>
      <% end %>
    </div>
  </div>