config/routes.rb
Rails.application.routes.draw do
  resources :users

  root 'conversations#index'
  resources :agents
  resources :conversations do
    member do
      post 'increment'
      get 'reset'
      post 'start_simulation'
    end
  end
  resources :messages
  resources :user
  resource :session, only: [:new, :create, :destroy]
  get "signup" => "users#new"
  get "signin" => "sessions#new"

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :name, presence: true
  validates :username, presence: true, uniqueness: true
  validates :email, presence: true,
                  format: { with: /\S+@\S+/ },
                  uniqueness: { case_sensitive: false }

  validates :password, length: { minimum: 8, allow_blank: true }

  has_many :conversations
  has_many :agents

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signin, except: [:new, :create]
  before_action :require_correct_user, only: [:edit, :update]



  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to user_path(user), notice: 'Account was successfully created.'
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    if user.update(user_params)
      redirect_to user_path(user), notice: 'Account was successfully updated.'
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :username, :email, :password)
  end

  def require_signin
    unless current_user
      redirect_to signin_url, alert: 'You must be signed in to access this page.'
    end
  end

  def require_correct_user
    user = User.find(params[:id])
    unless current_user == user
      redirect_to root_url
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user, html: { class: 'form-horizontal', role: 'form' } do |f| %>
  <div class="form-group">
    <%= f.label :name, class: 'control-label col-sm-2' %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :username, class: 'control-label col-sm-2' %>
    <div class="col-sm-10">
      <%= f.text_field :username, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :email, class: 'control-label col-sm-2' %>
    <div class="col-sm-10">
      <%= f.text_field :email, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :password, class: 'control-label col-sm-2' %>
    <div class="col-sm-10">
      <%= f.password_field :password, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation, "Confirm Password", class: 'control-label col-sm-2' %>
    <div class="col-sm-10">
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <% if @user.new_record? %>
        <%= f.submit "Create Account", class: 'btn btn-primary' %>
      <% else %>
        <%= f.submit "Update Account", class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="m-5">
    <h1>Edit Account</h1>
    <%= render "form", user: @user %>
</div>

app/views/users/new.html.erb
<div class="m-5">

<h1>Create an account</h1>
    <%= render "form", user: @user %>
    <div>
        <%= link_to "Sign In", signin_path %>
    </div>
</div>

app/views/users/show.html.erb
<div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card">
          <div class="card-header">
            <h1 class="card-title"><%= @user.name %></h1>
          </div>
          <div class="card-body">
            <h2 class="card-subtitle mb-2 text-muted"><%= mail_to(@user.email) %></h2>
            <% if current_user == @user %>
              <%= link_to "Edit", edit_user_path(@user), class: "btn btn-primary" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>