config/routes.rb
Rails.application.routes.draw do
  resources :users

  root 'conversations#index'
  resources :agents
  resources :conversations do
    member do
      post 'increment'
      get 'reset'
      post 'start_simulation'
    end
  end
  resources :messages
  resources :user
  resource :session, only: [:new, :create, :destroy]
  get "signup" => "users#new"
  get "signin" => "sessions#new"

end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand px-4" href="/">Run the Matrix</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav me-auto">
            <li class="nav-item active">
                <%= link_to "Home", root_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Agents", agents_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Conversations", conversations_path, class: "nav-link" %>
            </li>
        </ul>
        <ul class="navbar-nav ms-auto mx-5">
            <% if current_user %>
                <li class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <%= current_user.name %>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><%= link_to "Sign Out", session_path, data: {turbo_method: :delete}, class: "dropdown-item" %></li>
                    </ul>
                </li>
            <% else %>
                <li class="nav-item">
                    <%= link_to "Sign Up", signup_path, class: "nav-link" %>
                </li>
            <% end %>
        </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Run the Matrix</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <%= yield %>
  </body>
</html>